import { RequiredDataFromCollectionSlug } from 'payload'

export const contactForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Contact Consultation Form',
  submitButtonLabel: 'Submit Request',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you for your request',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Our team will contact you within 24 hours.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  emails: [],
  fields: [
    {
      name: 'firstName',
      blockName: 'firstName',
      blockType: 'text',
      label: 'First Name',
      required: true,
      width: 50,
    },
    {
      name: 'lastName',
      blockName: 'lastName',
      blockType: 'text',
      label: 'Last Name',
      required: true,
      width: 50,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email Address',
      required: true,
      width: 50,
    },
    {
      name: 'phone',
      blockName: 'phone',
      blockType: 'text',
      label: 'Phone Number',
      required: true,
      width: 50,
    },
    {
      name: 'projectType',
      blockName: 'projectType',
      blockType: 'select',
      label: 'Project Type',
      required: true,
      width: 100,
      options: [
        { label: 'Residential Solar Installation', value: 'residential' },
        { label: 'Commercial Solar Installation', value: 'commercial' },
        { label: 'Energy Consultation', value: 'consultation' },
        { label: 'Maintenance & Service', value: 'maintenance' },
        { label: 'Other', value: 'other' },
      ],
    },
    {
      name: 'location',
      blockName: 'location',
      blockType: 'text',
      label: 'Location / City',
      required: false,
      width: 100,
    },
    {
      name: 'message',
      blockName: 'message',
      blockType: 'textarea',
      label: 'Message',
      required: false,
      width: 100,
    },
    {
      name: 'consent',
      blockName: 'consent',
      blockType: 'checkbox',
      label: 'I agree to be contacted regarding my inquiry and accept the',
      required: true,
      width: 100,
    },
  ],
}
